global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: "qkd_client"
    static_configs:
      - targets: ["host.docker.internal:8001"]  # Mac/Windows „ÅÆ Docker Desktop
        labels:
          role: "client"
  - job_name: "qkd_server"
    static_configs:
      - targets: ["host.docker.internal:8002"]
        labels:
          role: "server"
